//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Zinc.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IZincListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class ZincBaseListener : IZincListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.grid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrid([NotNull] ZincParser.GridContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.grid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrid([NotNull] ZincParser.GridContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.gridMeta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGridMeta([NotNull] ZincParser.GridMetaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.gridMeta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGridMeta([NotNull] ZincParser.GridMetaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.ver"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVer([NotNull] ZincParser.VerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.ver"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVer([NotNull] ZincParser.VerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.tagsNoComma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTagsNoComma([NotNull] ZincParser.TagsNoCommaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.tagsNoComma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTagsNoComma([NotNull] ZincParser.TagsNoCommaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.tagsCommaOk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTagsCommaOk([NotNull] ZincParser.TagsCommaOkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.tagsCommaOk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTagsCommaOk([NotNull] ZincParser.TagsCommaOkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] ZincParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] ZincParser.TagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.tagMarker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTagMarker([NotNull] ZincParser.TagMarkerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.tagMarker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTagMarker([NotNull] ZincParser.TagMarkerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.tagPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTagPair([NotNull] ZincParser.TagPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.tagPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTagPair([NotNull] ZincParser.TagPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.cols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCols([NotNull] ZincParser.ColsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.cols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCols([NotNull] ZincParser.ColsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.col"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCol([NotNull] ZincParser.ColContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.col"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCol([NotNull] ZincParser.ColContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRow([NotNull] ZincParser.RowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRow([NotNull] ZincParser.RowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.val"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal([NotNull] ZincParser.ValContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.val"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal([NotNull] ZincParser.ValContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] ZincParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] ZincParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.dict"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDict([NotNull] ZincParser.DictContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.dict"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDict([NotNull] ZincParser.DictContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.nestedgrid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedgrid([NotNull] ZincParser.NestedgridContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.nestedgrid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedgrid([NotNull] ZincParser.NestedgridContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.scalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalar([NotNull] ZincParser.ScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.scalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalar([NotNull] ZincParser.ScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZincParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] ZincParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZincParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] ZincParser.BoolContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
